import {state,today,save,applyGrade,streak,learningHistory,rememberLearning,flush} from '../store.js';import {$,esc,hero,busy,toast} from '../ui.js';import {call} from '../ai/client.js';import {homework,grading,studyScope} from '../ai/prompts.js';
const types={concept:'基础理解',recall:'画面回忆',contrast:'对照理解',scenario:'情境解读',spread:'牌阵练习',symbol:'象征拆解',reverse:'逆位思考'};
export function validateTasks(value,cards,count,scope=null,catalog=cards,spreads=[]){if(!value||!Array.isArray(value.tasks)||value.tasks.length!==count||typeof value.focus!=='string')throw Error();const ids=new Set();for(const t of value.tasks){if(!Number.isInteger(t.id)||ids.has(t.id)||!types[t.type]||!Array.isArray(t.cards)||(t.type!=='concept'&&!t.cards.length)||t.cards.some(id=>!cards.some(c=>c.id===id))||!['prompt','hint','rubric'].every(k=>typeof t[k]==='string')||!t.prompt||!t.rubric)throw Error();if(scope){
 if(t.type==='reverse'&&!scope.reverse||t.type==='symbol'&&!scope.symbols||t.type==='spread'&&!scope.spreadIds.length)throw Error();
 const text=[t.prompt,t.hint,t.rubric].join(' ');
 for(const c of catalog)if(!scope.cardIds.includes(c.id)&&[c.name_cn,c.name_en,c.id].some(name=>text.toLowerCase().includes(name.toLowerCase())))throw Error();
 for(const spread of spreads)if(!scope.spreadIds.includes(spread.id)&&text.includes(spread.name))throw Error();
 if(!scope.reverse&&/逆位|倒置/.test(text))throw Error();
 if(typeof t.learningPoint!=='string'||!scope.topics.includes(t.learningPoint))throw Error();
 }ids.add(t.id);}}
export function validateGrade(g,tasks){if(!g||!Array.isArray(g.perTask)||g.perTask.length!==tasks.length||!Array.isArray(g.weakPoints)||g.weakPoints.some(x=>typeof x!=='string')||typeof g.nextFocus!=='string')throw Error();const ids=new Set();for(const p of g.perTask){if(ids.has(p.id)||!tasks.some(t=>t.id===p.id)||!Number.isFinite(p.score)||!Number.isFinite(p.max)||p.max<=0||p.score<0||p.score>p.max||!Array.isArray(p.correct)||!Array.isArray(p.missing)||[...p.correct,...p.missing].some(x=>typeof x!=='string')||typeof p.comment!=='string')throw Error();ids.add(p.id);}g.total=g.perTask.reduce((a,p)=>a+p.score,0);g.max=g.perTask.reduce((a,p)=>a+p.max,0);}
export function taskHTML(record,cards){return record.tasks.map((t,i)=>{const g=record.grade?.perTask?.find(p=>p.id===t.id);return `<article class="panel task"><div class="row between"><span class="task-number">练习 ${String(i+1).padStart(2,'0')}</span><span class="pill">${t.learningSource==='review'?'温习 · ':''}${types[t.type]||'解读练习'}</span></div><h3>${esc(t.prompt)}</h3><div class="task-cards">${t.cards.map(id=>{const c=cards.find(c=>c.id===id);return c?`<a href="#/cards/${c.id}"><img src="./${c.image}" alt="${c.name_cn}" loading="lazy"><small>${c.name_cn}</small></a>`:'';}).join('')}</div>${t.hint?`<details><summary>给我一点提示</summary><p class="muted">${esc(t.hint)}</p></details>`:''}<label for="answer-${i}">你的理解</label><textarea id="answer-${i}" data-answer="${i}" placeholder="先说说你看到了什么，再写下你的理解…" ${record.status==='graded'?'readonly':''}>${esc(record.answers[i]||'')}</textarea>${g?`<div class="grade"><span class="gold">${g.score} / ${g.max}</span>${g.correct.map(x=>`<p class="success">✓ ${esc(x)}</p>`).join('')}${g.missing.map(x=>`<p class="missing">↗ ${esc(x)}</p>`).join('')}<p>${esc(g.comment)}</p></div>`:''}</article>`;}).join('');}
export function bindAnswers(record){document.querySelectorAll('[data-answer]').forEach(el=>el.oninput=()=>{record.answers[Number(el.dataset.answer)]=el.value;save();});}
export async function gradeRecord(record){if(record.status==='graded')return record.grade;if(record.status==='submitted')throw new Error('正在批改这份练习，请稍候。');if(record.answers.length<record.tasks.length||record.tasks.some((_,i)=>!record.answers[i]?.trim()))throw new Error('请先写完每一道题，再提交批改。');record.status='submitted';save();try{const grade=await call({system:grading(state.settings.tone),user:{tasks:record.tasks,answers:record.answers},json:true,validate:g=>validateGrade(g,record.tasks)});record.grade=grade;record.status='graded';if(record.spreadId&&state.spreads[record.spreadId]){state.spreads[record.spreadId].practiced++;state.spreads[record.spreadId].status='familiar';}applyGrade(record.tasks,grade);save();return grade;}catch(e){record.status='pending';save();throw e;}}
export function validateScope(scope,cards,spreads){
 if(!scope||!Array.isArray(scope.cardIds)||!Array.isArray(scope.spreadIds)||!Array.isArray(scope.topics)||!scope.topics.length||scope.topics.some(t=>typeof t!=='string'||!t.trim())||scope.cardIds.some(id=>!cards.some(c=>c.id===id))||scope.spreadIds.some(id=>!spreads.some(s=>s.id===id))||typeof scope.reverse!=='boolean'||typeof scope.symbols!=='boolean')throw Error();
 scope.cardIds=[...new Set(scope.cardIds)];scope.spreadIds=[...new Set(scope.spreadIds)];
}
let generationPending=false;
export async function generateFromStudy(draft,cards,spreads){
 const scope=structuredClone(draft.scope);validateScope(scope,cards,spreads);
 const allowed=cards.filter(c=>scope.cardIds.includes(c.id));const count=state.settings.dailyTaskCount;
 const reviewSources=draft.reviewSources||[];const reviewCount=reviewSources.length?(draft.notes.trim()?Math.max(1,Math.floor(count/3)):count):0;
 const result=await call({system:homework,json:true,user:{count,reviewCount,reviewSources,studyNotes:draft.notes,scope,cards:allowed.map(c=>({id:c.id,name:c.name_cn})),spreads:spreads.filter(s=>scope.spreadIds.includes(s.id))},validate:v=>{validateTasks(v,allowed,count,scope,cards,spreads);if(reviewSources.length&&(v.tasks.filter(t=>t.learningSource==='review').length!==reviewCount||v.tasks.some(t=>!['today','review'].includes(t.learningSource))))throw Error();}});
 return {date:draft.date,studyNotes:draft.notes,reviewSources,studyScope:scope,...result,answers:result.tasks.map(()=>''),status:'pending'};
}
function composer(cards,spreads){
 const history=learningHistory().filter(r=>r.date<today());
 if(!state.studyDraft||state.studyDraft.date!==today())state.studyDraft={date:today(),notes:'',scope:null};
 const draft=state.studyDraft;draft.reviewSources??=[];
 const render=()=>{const scope=draft.scope;$('#study-composer').innerHTML=`<section class="panel study-composer"><div class="eyebrow">先记录，再练习</div><h2>今天，你学了什么？</h2><p class="muted section">写下学过的牌、知识点和还没学到的部分。题目会以这份记录为范围。</p><label for="study-notes" class="section">今日学习内容</label><textarea id="study-notes" maxlength="6000" placeholder="例如：今天学了愚者和魔术师的正位关键词，以及两张牌的区别。还没有学习逆位、占星和牌阵。">${esc(draft.notes)}</textarea><p class="muted study-help">也可以只写基础知识，如四种花色的元素；不必先学某张牌。</p><button id="save-learning" class="section">保存今日学习记录</button><details class="section review-picker" ${draft.reviewSources.length?'open':''}><summary>加入以前学过的内容${draft.reviewSources.length?` · 已选 ${draft.reviewSources.length} 天`:''}</summary><p class="muted study-help">选择想复习的日期。有新内容时约三分之一题目复习旧知识（至少 1 题）；今天只想复习，也可以不填新内容。</p>${history.map(r=>`<label class="scope-choice review-choice"><input type="checkbox" data-review-date="${r.date}" ${draft.reviewSources.some(s=>s.date===r.date)?'checked':''}><span><strong>${r.date}</strong><span class="review-note">${esc(r.notes)}</span></span></label>`).join('')||'<p class="muted section">还没有往日记录。保存今天的学习内容后，明天就能在这里选取。</p>'}</details><button id="prepare-study" class="section" ${generationPending?'disabled':''}>${scope?'重新整理学习范围':'整理学习范围'}</button>${scope?`<div class="study-scope section"><h3>这次只练这些</h3><p class="muted study-help">核对后再出题；未学过的项目可以取消勾选。</p><label>学习要点（每行一个）<textarea id="study-topics">${esc(scope.topics.join('\n'))}</textarea></label><div class="row section">${scope.cardIds.map(id=>`<label class="scope-choice"><input type="checkbox" data-scope-card="${id}" checked>${esc(cards.find(c=>c.id===id).name_cn)}</label>`).join('')||'<p class="muted">没有指定牌面，将练习你记录的基础知识。</p>'}</div><div class="row section">${scope.spreadIds.map(id=>`<label class="scope-choice"><input type="checkbox" data-scope-spread="${id}" checked>${esc(spreads.find(s=>s.id===id).name)}</label>`).join('')}</div><div class="row section"><label class="scope-choice"><input id="scope-reverse" type="checkbox" ${scope.reverse?'checked':''}>包含逆位</label><label class="scope-choice"><input id="scope-symbols" type="checkbox" ${scope.symbols?'checked':''}>包含画面象征</label></div><button id="generate-homework" class="primary section" ${generationPending?'disabled':''}>按这个范围生成 ${state.settings.dailyTaskCount} 道题</button></div>`:''}</section>`;
 $('#study-notes').oninput=e=>{draft.notes=e.target.value;draft.scope=null;save();$('.study-scope')?.remove();};
 $('#save-learning').onclick=()=>{if(!draft.notes.trim()){toast('先写下今天学了什么。');return;}rememberLearning(draft.date,draft.notes);save();const stored=flush();toast(stored?'学习记录已保存，之后可以加入复习。':'未能保存，请先导出备份。');if(stored)view(cards,spreads,null,true);};
 document.querySelectorAll('[data-review-date]').forEach(el=>el.onchange=()=>{draft.reviewSources=Array.from(document.querySelectorAll('[data-review-date]:checked'),el=>{const r=history.find(r=>r.date===el.dataset.reviewDate);return {date:r.date,notes:r.notes};});draft.scope=null;save();$('.study-scope')?.remove();});
 $('#prepare-study').onclick=e=>busy(e.currentTarget,async()=>{const notes=draft.notes.trim();const reviewSources=structuredClone(draft.reviewSources);if(!notes&&!reviewSources.length)throw new Error('先填写今日学习内容，或选择以前的学习记录。');rememberLearning(draft.date,notes);save();const result=await call({system:studyScope,json:true,user:{studyNotes:notes,reviewSources,cards:cards.map(c=>({id:c.id,name:c.name_cn})),spreads:spreads.map(s=>({id:s.id,name:s.name}))},validate:v=>validateScope(v,cards,spreads)});if(draft.notes.trim()!==notes||JSON.stringify(draft.reviewSources)!==JSON.stringify(reviewSources))return;draft.scope=result;save();if($('#study-composer'))render();});
 $('#generate-homework')?.addEventListener('click',e=>busy(e.currentTarget,async()=>{if(generationPending)throw new Error('正在生成作业，请稍候。');const current=draft.scope;if(!current)throw new Error('学习内容已修改，请重新整理范围。');current.topics=$('#study-topics').value.split('\n').map(t=>t.trim()).filter(Boolean);current.cardIds=Array.from(document.querySelectorAll('[data-scope-card]:checked'),el=>el.dataset.scopeCard);current.spreadIds=Array.from(document.querySelectorAll('[data-scope-spread]:checked'),el=>el.dataset.scopeSpread);current.reverse=$('#scope-reverse').checked;current.symbols=$('#scope-symbols').checked;if(!current.topics.length)throw new Error('请至少保留一个学习要点。');save();const snapshot=structuredClone(draft);generationPending=true;$('#study-composer').querySelectorAll('input,textarea,button').forEach(el=>el.disabled=true);try{const h=await generateFromStudy(snapshot,cards,spreads);state.homework.push(h);save();if($('#study-composer'))view(cards,spreads,h);else toast('今日作业已生成，可在作业页查看。');}finally{generationPending=false;if($('#study-composer'))render();}}));
 };render();
}
export function view(cards,spreads,record=null,edit=false){
 learningHistory();
 record=record||[...state.homework].reverse().find(h=>h.date===today()&&!h.spreadId);
 const historical=record&&record.date!==today();
 $('#view').innerHTML=hero(`${(edit?today():(record?.date||today())).replaceAll('-',' · ')} · 连续学习 ${streak()} 天`,historical?'翻阅过去的思考':'今天，让理解再深一点','从今天学过的内容出发，一点点巩固理解。','✎')+
 ((!record||edit)?'<div id="study-composer"></div>':`<section class="panel"><div class="row between"><h3>${record.spreadId?'牌阵练习':record.studyNotes?'这份作业的学习范围':'这份作业使用了原来的自动出题方式'}</h3>${!record.spreadId?'<button id="edit-study">填写学习内容，重新出题</button>':''}</div><p class="muted section">${esc(record.studyNotes||(record.spreadId?record.focus:'')||'可以填写实际学过的内容，生成一份范围更明确的新作业。旧作业会保留在手记里。')}</p>${record.reviewSources?.length?`<details class="section"><summary>这次复习了 ${record.reviewSources.length} 天的学习内容</summary>${record.reviewSources.map(r=>`<p class="muted section">${esc(r.date)}\n${esc(r.notes)}</p>`).join('')}</details>`:''}</section><p class="note section">${esc(record.focus||'把牌面、牌位和情境连接起来。')}</p><div class="stack section">${taskHTML(record,cards)}</div>${record.status==='graded'?`<section class="panel section"><div class="row between"><h2>这一页，已写下成长</h2><span class="score">${Math.round(record.grade.total/record.grade.max*100)}<small> / 100</small></span></div><p class="section">${esc(record.grade.nextFocus)}</p><p class="muted">${record.grade.weakPoints.map(esc).join(' · ')}</p></section>`:'<button id="submit" class="primary section">✧ 提交给星语批改</button>'}`)+
 `<details class="section learning-journal"><summary>已保存的学习记录 · ${learningHistory().length} 天</summary><p class="muted">学习记录长期保存在此设备，导出学习数据时也会一起备份。</p>${learningHistory().map(r=>`<article class="panel section"><h3>${esc(r.date)}</h3><p class="muted section">${esc(r.notes)}</p></article>`).join('')||'<p class="muted section">还没有保存的学习记录。</p>'}</details><section class="history"><h3>学习手记</h3>${[...state.homework].reverse().map(h=>`<button data-history="${state.homework.indexOf(h)}"><span>${h.date} · ${esc(h.spreadName||'每日作业')}<small class="history-scope">${esc(h.studyNotes?.slice(0,55)||'')}</small></span><span class="muted">${h.status==='graded'?'已批改':'继续作答'} →</span></button>`).join('')||'<p class="muted section">你的第一份练习，会从这里开始。</p>'}</section>`;
 if(!record||edit)composer(cards,spreads);
 if(record&&!edit){bindAnswers(record);$('#submit')?.addEventListener('click',e=>busy(e.currentTarget,async()=>{await gradeRecord(record);view(cards,spreads,record);}));$('#edit-study')?.addEventListener('click',()=>{if(!state.studyDraft||state.studyDraft.date!==today())state.studyDraft={date:today(),notes:record.studyNotes||'',scope:null};save();view(cards,spreads,record,true);window.scrollTo(0,0);});}
 document.querySelectorAll('[data-history]').forEach(b=>b.onclick=()=>{view(cards,spreads,state.homework[Number(b.dataset.history)]);window.scrollTo(0,0);});
}
