import {state,save,today} from '../store.js';import {$,esc,hero,showSheet,sheetHeader,busy} from '../ui.js';import {taskHTML,bindAnswers,gradeRecord} from './homework.js';
export function board(s,mini=false,draw=[]){
 const kind=s.cardCount<=3?'simple':s.id==='celtic-cross'?'cross':'complex';
 return `<div class="spread-board ${mini?'mini':''} layout-${kind}" aria-label="${esc(s.name)}牌位示意">${s.positions.map((p,i)=>{
 const tag=mini?'span':'button',card=draw[i];
 return `<${tag} class="position ${p.rotate?'crossing':''} ${card?'dealt':''}" style="left:${p.x}%;top:${p.y}%;--rotation:${p.rotate||0}deg" ${mini?'aria-hidden="true"':`data-position="${i}" aria-label="${p.index} ${esc(p.label)}"`}><span class="position-face">${card?`<img src="./${card.image}" alt="${esc(card.name_cn)}" loading="lazy">`:'<span class="position-ornament" aria-hidden="true">✧</span>'}</span><span class="position-number">${p.index}</span></${tag}>`;
 }).join('')}</div>`;
}
function positionGuide(s,draw){return `<div class="position-guide" aria-label="按顺序认识牌位">${s.positions.map((p,i)=>`<button class="guide-position" data-position="${i}"><span class="guide-number">${p.index}</span><span><strong>${esc(p.label)}</strong><small>${esc(draw[i]?.name_cn||p.question)}</small></span><span class="guide-arrow" aria-hidden="true">›</span></button>`).join('')}</div>`;}
export function list(spreads){$('#view').innerHTML=hero('从单张牌，到完整的故事','让牌与牌，开始对话','认识每个位置的提问，练习把分散的线索连接起来。','✣')+`<div class="spread-grid">${spreads.map(s=>`<a class="panel spread-card" href="#/spreads/${s.id}">${board(s,true)}<div class="row between"><h3>${s.name}</h3><span class="pill">${['','入门','进阶','深入'][s.difficulty]}</span></div><p>${s.when_to_use}</p><div class="row section"><span class="pill">${s.cardCount} 张牌</span><small>${state.spreads[s.id]?`已练习 ${state.spreads[s.id].practiced} 次`:'等待探索'}</small></div></a>`).join('')}</div>`;}
export function detail(s,cards){if(!state.spreads[s.id]){state.spreads[s.id]={status:'learning',practiced:0};save();}let record=state.homework.find(h=>h.spreadId===s.id&&h.status!=='graded');const render=()=>{const draw=record?record.tasks[record.tasks.length-1].cards.map(id=>cards.find(c=>c.id===id)):[];$('#view').innerHTML=`<a class="back" href="#/spreads">← 返回牌阵</a>`+hero(`${s.cardCount} 张牌 · ${['','入门','进阶','深入'][s.difficulty]}`,s.name,s.when_to_use,'✣')+`<section class="spread-map-section"><div class="row between spread-map-heading"><h2>牌位图解</h2><small>点击编号或下方牌位，了解含义</small></div>${board(s,false,draw)}${positionGuide(s,draw)}</section>`+`<div class="panel section prose spread-reading"><h3>如何串起这个故事</h3><p>${esc(s.reading_tips)}</p><h3>容易走入的误区</h3><p>${esc(s.common_mistakes)}</p></div>${record?`<section class="stack section">${taskHTML(record,cards)}</section>${record.status==='graded'?`<div class="note section">${esc(record.grade.nextFocus)}</div><button id="practice" class="section">再练习一次</button>`:'<button id="grade-spread" class="primary section">提交牌阵解读</button>'}`:'<button id="practice" class="primary section">开始空盘练习</button><p class="muted section">随机发牌，练习每个牌位，再把它们串成一个故事。</p>'}`;document.querySelectorAll('[data-position]').forEach(b=>b.onclick=()=>{const p=s.positions[Number(b.dataset.position)];showSheet(sheetHeader(`${p.index} · ${p.label}`)+`<p class="section prose">${esc(p.question)}</p><p class="muted section">${esc(s.reading_tips)}</p>`);});$('#practice')?.addEventListener('click',()=>{const shuffled=[...cards];for(let i=shuffled.length-1;i>0;i--){const a=new Uint32Array(1);crypto.getRandomValues(a);const j=a[0]%(i+1);[shuffled[i],shuffled[j]]=[shuffled[j],shuffled[i]];}const drawn=shuffled.slice(0,s.cardCount);record={date:today(),spreadId:s.id,spreadName:s.name,focus:s.reading_tips,status:'pending',answers:Array(s.cardCount+1).fill(''),tasks:[...s.positions.map((p,i)=>({id:i+1,type:'spread',cards:[drawn[i].id],prompt:`${p.index}. ${p.label}：${p.question}`,hint:s.reading_tips,rubric:`在${s.name}牌阵中，结合${p.label}牌位与${drawn[i].name_cn}解读。${p.question}避免宿命论。`})),{id:s.cardCount+1,type:'spread',cards:drawn.map(c=>c.id),prompt:s.positions.map((p,i)=>`${p.index}. ${p.label}：${drawn[i].name_cn}——${p.question}`).join('\n')+'\n\n请逐位解读，并用一段话连接整个牌阵。',hint:s.reading_tips,rubric:'结合每个牌位问题与对应牌义，区分观察、推测与建议，串联各牌关系；避免宿命论。'+s.common_mistakes}]};state.homework.push(record);save();render();});if(record){bindAnswers(record);$('#grade-spread')?.addEventListener('click',e=>busy(e.currentTarget,async()=>{await gradeRecord(record);save();render();}));}};render();}
